#!/usr/bin/env bash
#
# install.sh — install / update the Figma design-to-code skill suite for Claude Code.
#
# Usage:
#   ./install.sh                 # install for the current user (~/.claude/skills)
#   ./install.sh --update        # update installed suite skills to the latest (no prompts)
#   ./install.sh --check         # report installed vs latest version, then exit
#   ./install.sh --project       # install into ./.claude/skills (this project only)
#   ./install.sh --dir <path>    # install into a custom skills directory
#   ./install.sh --force         # overwrite existing skills without prompting
#   ./install.sh --no-notify     # install/update without the daily update-check hook
#   ./install.sh --uninstall     # remove the suite skills, commands, and update-check hook
#
# Remote one-liners (no clone needed):
#   curl -fsSL https://raw.githubusercontent.com/Peeradonte48/product-design-skill/main/install.sh | bash
#   curl -fsSL .../install.sh | bash -s -- --update    # update to the latest
#   curl -fsSL .../install.sh | bash -s -- --check     # check for updates, change nothing
#
# Update notifications: by default the installer adds a Claude Code SessionStart
# hook that checks GitHub (at most once a day) for a newer version and prints a
# one-line notice. It fails silently when offline. Opt out with --no-notify; it
# is removed by --uninstall.
#
set -euo pipefail

REPO="Peeradonte48/product-design-skill"
BRANCH="main"
TARBALL="https://codeload.github.com/${REPO}/tar.gz/refs/heads/${BRANCH}"
MANIFEST_NAME=".product-design-skill.version"
NOTIFY_SCRIPT_NAME=".product-design-skill-notify.sh"
LASTCHECK_NAME=".product-design-skill.lastcheck"
CHANGELOG_URL="https://github.com/${REPO}/blob/${BRANCH}/CHANGELOG.md"
UPDATE_CMD="curl -fsSL https://raw.githubusercontent.com/${REPO}/${BRANCH}/install.sh | bash -s -- --update"
SKILLS=(
  "implement-figma-design"
  "figjam-to-use-case-narrative"
  "use-case-narrative-to-prototype"
  "figma-design-to-working-prototype"
  "figjam-sitemap-to-spec"
  "page-to-figma"
  "critique-figma-design"
  "verify-design-match"
  "figma-to-dev-docs"
  "harden-doc"
  "biz-review"
  "spec-to-brief"
)
# Single-file slash commands shipped alongside the skills (installed into the
# sibling commands/ dir, e.g. ~/.claude/commands). Add the filename here for
# every command shipped under the repo-root commands/ dir.
COMMANDS=(
  "update-design-skills.md"
)

# --- arg parsing -----------------------------------------------------------
TARGET=""
FORCE=0
UNINSTALL=0
UPDATE=0
CHECK=0
NOTIFY=1
TARGET_KIND="user"   # user | project | custom — gates auto-registration of the hook
while [ $# -gt 0 ]; do
  case "$1" in
    --project)   TARGET="$(pwd)/.claude/skills"; TARGET_KIND="project"; shift ;;
    --dir)       TARGET="${2:?--dir needs a path}"; TARGET_KIND="custom"; shift 2 ;;
    --force)     FORCE=1; shift ;;
    --update)    UPDATE=1; FORCE=1; shift ;;
    --check)     CHECK=1; shift ;;
    --no-notify) NOTIFY=0; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help)   sed -n '2,24p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done
[ -n "$TARGET" ] || TARGET="${HOME}/.claude/skills"
MANIFEST="${TARGET}/${MANIFEST_NAME}"
NOTIFY_SCRIPT="${TARGET}/${NOTIFY_SCRIPT_NAME}"
SETTINGS="$(dirname "$TARGET")/settings.json"   # ~/.claude/settings.json or <proj>/.claude/settings.json
CMD_TARGET="$(dirname "$TARGET")/commands"      # ~/.claude/commands or <proj>/.claude/commands

say() { printf '  %s\n' "$1"; }
contains() { local n="$1"; shift; local x; for x in "$@"; do [ "$x" = "$n" ] && return 0; done; return 1; }
installed_version() { [ -f "$MANIFEST" ] && (grep '^version=' "$MANIFEST" 2>/dev/null | head -1 | cut -d= -f2-) || true; }

# --- update-notification hook ----------------------------------------------
# Write the SessionStart notifier script. It reads the installed version from the
# manifest next to it, fetches the latest VERSION from GitHub at most once a day,
# and (only when they differ) prints a SessionStart JSON notice. Fails silently.
write_notifier() {
  local dest="$1"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by product-design-skill install.sh — checks for suite updates.\n'
    printf 'REPO=%q\n' "$REPO"
    printf 'BRANCH=%q\n' "$BRANCH"
    printf 'CHANGELOG_URL=%q\n' "$CHANGELOG_URL"
    cat <<'NOTIFY_EOF'
set -u
DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd)" || exit 0
MANIFEST="$DIR/.product-design-skill.version"
LASTCHECK="$DIR/.product-design-skill.lastcheck"
[ -f "$MANIFEST" ] || exit 0

now="$(date +%s 2>/dev/null)" || exit 0
if [ -f "$LASTCHECK" ]; then
  last="$(cat "$LASTCHECK" 2>/dev/null || echo 0)"
  case "$last" in ''|*[!0-9]*) last=0 ;; esac
  [ $((now - last)) -ge 86400 ] || exit 0
fi
echo "$now" > "$LASTCHECK" 2>/dev/null || true   # throttle even when offline

command -v curl >/dev/null 2>&1 || exit 0
installed="$(grep '^version=' "$MANIFEST" 2>/dev/null | head -1 | cut -d= -f2-)"
[ -n "$installed" ] || exit 0
latest="$(curl -fsSL --max-time 3 "https://raw.githubusercontent.com/${REPO}/${BRANCH}/VERSION" 2>/dev/null | head -1 | tr -d '[:space:]')"
[ -n "$latest" ] || exit 0
[ "$latest" != "$installed" ] || exit 0

cmd="curl -fsSL https://raw.githubusercontent.com/${REPO}/${BRANCH}/install.sh | bash -s -- --update"
user_msg="product-design-skill ${latest} is available (you have ${installed}). Update: ${cmd}  •  Changelog: ${CHANGELOG_URL}"
agent_msg="A newer product-design-skill suite version (${latest}) is available; the user has ${installed}. If they want it, offer to run: ${cmd}"

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' \
  "$(esc "$user_msg")" "$(esc "$agent_msg")"
exit 0
NOTIFY_EOF
  } > "$dest"
  chmod +x "$dest" 2>/dev/null || true
}

# Idempotently add our SessionStart hook to a settings.json. Returns 0 on success
# (registered or already present), 1 on write error, 2 if no JSON tool is available.
register_hook() {
  local script="$1" settings="$2" status
  mkdir -p "$(dirname "$settings")"
  [ -f "$settings" ] && [ -s "$settings" ] || echo '{}' > "$settings"
  cp "$settings" "${settings}.pds-bak" 2>/dev/null || true
  if command -v python3 >/dev/null 2>&1; then
    status="$(PDS_SCRIPT="$script" PDS_SETTINGS="$settings" python3 - <<'PY'
import json, os, sys
p = os.environ["PDS_SETTINGS"]; cmd = os.environ["PDS_SCRIPT"]
try:
    with open(p) as f: data = json.load(f)
except Exception:
    data = {}
if not isinstance(data, dict): data = {}
hooks = data.setdefault("hooks", {})
if not isinstance(hooks, dict): hooks = {}; data["hooks"] = hooks
ss = hooks.get("SessionStart")
if not isinstance(ss, list): ss = []; hooks["SessionStart"] = ss
def present():
    for e in ss:
        if isinstance(e, dict):
            for h in e.get("hooks", []) or []:
                if isinstance(h, dict) and h.get("command") == cmd: return True
    return False
if present():
    print("present"); sys.exit(0)
ss.append({"matcher": "startup", "hooks": [{"type": "command", "command": cmd, "timeout": 10}]})
with open(p, "w") as f: json.dump(data, f, indent=2); f.write("\n")
print("registered")
PY
)" || { say "notify: could not update ${settings} (left unchanged)"; return 1; }
  elif command -v jq >/dev/null 2>&1; then
    local tmp; tmp="$(mktemp)"
    if jq --arg cmd "$script" '
        .hooks = (.hooks // {}) | .hooks.SessionStart = (.hooks.SessionStart // []) |
        if any(.hooks.SessionStart[]?; (.hooks[]?.command) == $cmd) then .
        else .hooks.SessionStart += [{matcher:"startup",hooks:[{type:"command",command:$cmd,timeout:10}]}] end
      ' "$settings" > "$tmp" 2>/dev/null; then
      mv "$tmp" "$settings"; status="registered"
    else
      rm -f "$tmp"; say "notify: could not update ${settings} (left unchanged)"; return 1
    fi
  else
    return 2
  fi
  case "$status" in
    present)    say "notify: daily update checks already enabled (${settings})" ;;
    *)          say "notify: daily update checks enabled (SessionStart hook → ${settings})" ;;
  esac
  return 0
}

# Remove our SessionStart hook from a settings.json (idempotent, leaves others).
deregister_hook() {
  local script="$1" settings="$2"
  [ -f "$settings" ] || return 0
  cp "$settings" "${settings}.pds-bak" 2>/dev/null || true
  if command -v python3 >/dev/null 2>&1; then
    PDS_SCRIPT="$script" PDS_SETTINGS="$settings" python3 - <<'PY' || return 0
import json, os
p = os.environ["PDS_SETTINGS"]; cmd = os.environ["PDS_SCRIPT"]
try:
    with open(p) as f: data = json.load(f)
except Exception:
    raise SystemExit(0)
if not isinstance(data, dict): raise SystemExit(0)
hooks = data.get("hooks")
if not isinstance(hooks, dict): raise SystemExit(0)
ss = hooks.get("SessionStart")
if not isinstance(ss, list): raise SystemExit(0)
new = []
for e in ss:
    if not isinstance(e, dict): new.append(e); continue
    hs = [h for h in e.get("hooks", []) or [] if not (isinstance(h, dict) and h.get("command") == cmd)]
    if hs: e = dict(e); e["hooks"] = hs; new.append(e)
if new: hooks["SessionStart"] = new
else: hooks.pop("SessionStart", None)
if not hooks: data.pop("hooks", None)
with open(p, "w") as f: json.dump(data, f, indent=2); f.write("\n")
PY
    say "notify: update-check hook removed from ${settings}"
  elif command -v jq >/dev/null 2>&1; then
    local tmp; tmp="$(mktemp)"
    if jq --arg cmd "$script" '
        if .hooks.SessionStart then
          .hooks.SessionStart = (.hooks.SessionStart
            | map(.hooks = ((.hooks // []) | map(select(.command != $cmd))))
            | map(select((.hooks // [] | length) > 0)))
          | (if (.hooks.SessionStart | length) == 0 then del(.hooks.SessionStart) else . end)
          | (if (.hooks | length) == 0 then del(.hooks) else . end)
        else . end
      ' "$settings" > "$tmp" 2>/dev/null; then
      mv "$tmp" "$settings"; say "notify: update-check hook removed from ${settings}"
    else rm -f "$tmp"; fi
  fi
}

# --- locate the skills/ source ---------------------------------------------
# Use the local checkout only when this script is a real FILE sitting next to a
# skills/ dir; otherwise download a tarball of the repo and use the skills/ dir
# inside it. When piped (curl … | bash) there is no script file — BASH_SOURCE[0]
# resolves to the CWD — so we must NOT treat a skills/ dir that merely happens to
# be in the current directory as the source; force remote in that case.
SELF="${BASH_SOURCE[0]:-}"
SCRIPT_DIR="$(cd "$(dirname "${SELF:-$0}")" && pwd)"
CLEANUP=""
trap '[ -n "$CLEANUP" ] && rm -rf "$CLEANUP"' EXIT

if [ -f "$SELF" ] && [ -d "${SCRIPT_DIR}/skills" ]; then
  SRC="${SCRIPT_DIR}/skills"
  MODE="local"
else
  MODE="remote"
  TMP="$(mktemp -d)"
  CLEANUP="$TMP"
  echo "Downloading ${REPO}@${BRANCH}…"
  curl -fsSL "$TARBALL" | tar -xzf - -C "$TMP"
  SRC="$(echo "$TMP"/*/skills)"   # extracted dir is REPO-BRANCH/
  if [ ! -d "$SRC" ]; then
    echo "Could not find skills/ in the downloaded archive." >&2
    exit 1
  fi
fi

# Latest version ships as a VERSION file at the repo root (next to skills/).
LATEST="$(cat "$(dirname "$SRC")/VERSION" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
[ -n "$LATEST" ] || LATEST="unknown"

# Slash commands live next to skills/ in the repo (commands/), and install into
# the sibling commands/ dir of the skills target.
CMD_SRC="$(dirname "$SRC")/commands"

# --- check (read-only; report and exit) ------------------------------------
if [ "$CHECK" -eq 1 ]; then
  inst="$(installed_version)"
  echo "product-design-skill — version check (${TARGET})"
  if [ -z "$inst" ]; then
    say "installed: (none detected, or installed before versioning)"
  else
    say "installed: ${inst}"
  fi
  say "latest:    ${LATEST}"
  if [ -n "$inst" ] && [ "$inst" = "$LATEST" ]; then
    say "✓ up to date"
  else
    say "↑ update available — run:"
    say "  ${UPDATE_CMD}"
    say "changelog: ${CHANGELOG_URL}"
  fi
  exit 0
fi

# --- uninstall -------------------------------------------------------------
if [ "$UNINSTALL" -eq 1 ]; then
  echo "Removing skills from: ${TARGET}"
  for s in "${SKILLS[@]}"; do
    if [ -d "${TARGET}/${s}" ]; then
      rm -rf "${TARGET:?}/${s}"; say "removed ${s}"
    else
      say "skip   ${s} (not installed)"
    fi
  done
  for c in "${COMMANDS[@]}"; do
    if [ -f "${CMD_TARGET}/${c}" ]; then
      rm -f "${CMD_TARGET}/${c}"; say "removed ${c}"
    else
      say "skip   ${c} (not installed)"
    fi
  done
  [ -f "$MANIFEST" ] && rm -f "$MANIFEST" && say "removed version manifest"
  deregister_hook "$NOTIFY_SCRIPT" "$SETTINGS"
  [ -f "$NOTIFY_SCRIPT" ] && rm -f "$NOTIFY_SCRIPT" && say "removed update-check script"
  [ -f "${TARGET}/${LASTCHECK_NAME}" ] && rm -f "${TARGET}/${LASTCHECK_NAME}"
  echo "Done."; exit 0
fi

# --- install / update ------------------------------------------------------
if [ "$UPDATE" -eq 1 ]; then
  echo "Updating Figma skill suite (${MODE}) → ${LATEST}  into: ${TARGET}"
  prev="$(installed_version)"; [ -n "$prev" ] && say "(was ${prev})"
else
  echo "Installing Figma skill suite (${MODE}) → ${LATEST}  into: ${TARGET}"
fi
mkdir -p "${TARGET}"

added=0; updated=0; unchanged=0; removed=0
for s in "${SKILLS[@]}"; do
  src="${SRC}/${s}"; dest="${TARGET}/${s}"
  if [ ! -d "$src" ]; then
    say "skip   ${s} (missing in source)"; continue
  fi
  if [ -d "$dest" ]; then
    if [ "$UPDATE" -eq 1 ]; then
      # only touch skills whose content actually changed
      if diff -rq -x '.DS_Store' "$src" "$dest" >/dev/null 2>&1; then
        say "unchanged ${s}"; unchanged=$((unchanged+1)); continue
      fi
    elif [ "$FORCE" -ne 1 ]; then
      printf '  %s already exists. Overwrite? [y/N] ' "$s"
      read -r ans </dev/tty || ans="n"
      case "$ans" in [yY]*) ;; *) say "skip   ${s}"; continue ;; esac
    fi
    rm -rf "$dest"; mkdir -p "$dest"; cp -R "${src}/." "$dest/"
    find "$dest" -name '.DS_Store' -type f -delete 2>/dev/null || true
    say "updated ${s}"; updated=$((updated+1))
  else
    mkdir -p "$dest"; cp -R "${src}/." "$dest/"
    find "$dest" -name '.DS_Store' -type f -delete 2>/dev/null || true
    say "installed ${s}"; added=$((added+1))
  fi
done

# --- slash commands (single files → sibling commands/ dir) -----------------
if [ -d "$CMD_SRC" ]; then
  mkdir -p "${CMD_TARGET}"
  for c in "${COMMANDS[@]}"; do
    src="${CMD_SRC}/${c}"; dest="${CMD_TARGET}/${c}"
    if [ ! -f "$src" ]; then
      say "skip   ${c} (missing in source)"; continue
    fi
    if [ -f "$dest" ]; then
      if [ "$UPDATE" -eq 1 ]; then
        if diff -q "$src" "$dest" >/dev/null 2>&1; then
          say "unchanged ${c}"; unchanged=$((unchanged+1)); continue
        fi
      elif [ "$FORCE" -ne 1 ]; then
        printf '  command %s already exists. Overwrite? [y/N] ' "$c"
        read -r ans </dev/tty || ans="n"
        case "$ans" in [yY]*) ;; *) say "skip   ${c}"; continue ;; esac
      fi
      cp "$src" "$dest"; say "updated ${c}"; updated=$((updated+1))
    else
      cp "$src" "$dest"; say "installed ${c}"; added=$((added+1))
    fi
  done
fi

# --- prune skills removed upstream (update only, only ones we installed) ----
if [ "$UPDATE" -eq 1 ] && [ -f "$MANIFEST" ]; then
  old_skills="$(grep '^skills=' "$MANIFEST" 2>/dev/null | head -1 | cut -d= -f2- || true)"
  for os in $old_skills; do
    if ! contains "$os" "${SKILLS[@]}" && [ -d "${TARGET}/${os}" ]; then
      rm -rf "${TARGET:?}/${os}"; say "removed ${os} (no longer in suite)"; removed=$((removed+1))
    fi
  done
  old_cmds="$(grep '^commands=' "$MANIFEST" 2>/dev/null | head -1 | cut -d= -f2- || true)"
  for oc in $old_cmds; do
    if ! contains "$oc" "${COMMANDS[@]}" && [ -f "${CMD_TARGET}/${oc}" ]; then
      rm -f "${CMD_TARGET}/${oc}"; say "removed ${oc} (no longer in suite)"; removed=$((removed+1))
    fi
  done
fi

# --- write version manifest ------------------------------------------------
{
  echo "version=${LATEST}"
  echo "installed=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date)"
  echo "skills=${SKILLS[*]}"
  echo "commands=${COMMANDS[*]}"
} > "$MANIFEST"

# --- update-check hook -----------------------------------------------------
# Always (re)write the script so updates ship fixes; register it unless opted out.
if [ "$NOTIFY" -eq 1 ]; then
  write_notifier "$NOTIFY_SCRIPT"
  if [ "$TARGET_KIND" = "custom" ]; then
    say "notify: wrote ${NOTIFY_SCRIPT} — register it in your settings.json manually to enable update checks"
  else
    register_hook "$NOTIFY_SCRIPT" "$SETTINGS" || \
      say "notify: install python3 or jq to auto-enable update checks (skipped)"
  fi
elif [ "$UPDATE" -eq 1 ]; then
  # --no-notify on update: tear down a previously installed hook
  deregister_hook "$NOTIFY_SCRIPT" "$SETTINGS"
  [ -f "$NOTIFY_SCRIPT" ] && rm -f "$NOTIFY_SCRIPT"
fi

echo
if [ "$UPDATE" -eq 1 ]; then
  echo "Updated to ${LATEST}: ${added} added, ${updated} updated, ${unchanged} unchanged, ${removed} removed."
else
  echo "Installed ${LATEST}."
fi
echo "Restart Claude Code (or run /doctor) so it picks up the changes."
echo "Check for updates anytime:  curl -fsSL https://raw.githubusercontent.com/${REPO}/${BRANCH}/install.sh | bash -s -- --check"
echo "What's new:  ${CHANGELOG_URL}"
[ "$NOTIFY" -eq 1 ] && [ "$TARGET_KIND" != "custom" ] && \
  echo "Daily update checks are on (disable with --no-notify, or remove via --uninstall)."
if [ "$UPDATE" -ne 1 ]; then
  echo "Invoke a skill by sharing a Figma/FigJam link, or type its name, e.g.:"
  echo "  implement-figma-design  •  figjam-to-use-case-narrative  •  use-case-narrative-to-prototype"
  echo "  figma-design-to-working-prototype  •  figjam-sitemap-to-spec  •  page-to-figma  •  spec-to-brief"
  echo "Run the command-only skills:  /critique-figma-design  •  /verify-design-match  •  /figma-to-dev-docs  •  /harden-doc <doc>  •  /biz-review <doc>"
  echo "Update from inside Claude Code anytime:  /update-design-skills"
fi
